### ISSUE TITLE
Could not determine react-native-codegen location

### ISSUE THREAD

**Issue by coniel** [mmazzarolo/react-native-monorepo-tools#2]
Thanks for this package and the tutorial series!

I'm setting up React Native as part of a [Typescript monorepo](https://github.com/NiGhTTraX/ts-monorepo). I'm using this package and get the error `Could not determine react-native-codegen location` when trying to build the iOS app (haven't tried Android yet).

I works fine if I add `react-native-codegen` to the `nohoist` list, but I'm thinking that the point of this package is not to need to do that, right?

**Comment by mmazzarolo** [comment]
Hi @coniel !  

Hard to say without seeing the codebase, but if you're using the `getMetroConfig` of this package (and you're already hoisting some of your libs) you should probably have either [`**/react-native-codegen`](https://github.com/mmazzarolo/react-native-universal-monorepo/blob/3f5be48c774bcbe3ad2e97896e6a4da9b784d5f4/package.json#L15) or [`**/react-native/**`](https://github.com/mmazzarolo/react-native-universal-monorepo/blob/3f5be48c774bcbe3ad2e97896e6a4da9b784d5f4/package.json#L13-L14) in your nohoist list.  

> but I'm thinking that the point of this package is not to need to do that, right?

The point of this package is to support Yarn workspaces monorepo that use `nohoist` 👍
